customer/urls.py
from django.urls import path
from. import views

app_name = "customer"

urlpatterns = [   
   path('',views.customer_home, name='customer_home'),
   path('store',views.store,name='store'),
   path('product/detail',views.product_detail,name='product_detail'),
   path('cart',views.cart,name='cart'),
   path('placeOrder',views.place_order,name='place_order'),
   path('order/successc',views.order_complete,name='order_complete'),
   path('dashboard',views.dashboard,name='dasboard'),
   path('seller/register',views.seller_register,name='seller_register'),
   path('seller/login',views.seller_login,name='seller_login'),
   path('customer/signup',views.customer_signup,name='customer_signup'),
   path('customer/login',views.customer_login,name='customer_login'),
   path('forgotPassword/customer',views.forgot_password_customer,name='forgot_password_customer'),
   path('forgotPassword/seller',views.forgot_password_seller,name='forgot_password_seller'),
   

]

eKart/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ekart/', include('eKart_admin.urls')),
    path('seller/', include('seller.urls')),
    path('', include('customer.urls'))


]

seller/urls.py
from django.urls import path
from. import views

app_name = "Seller"

urlpatterns = [   
    path('',views.seller_home,name="seller_home"),
    path('product/add',views.add_product,name="add_product"),
    # path('add_category',views.add_category,name="add_category"),
    path('product',views.view_products,name="view_product"),
    # path('view_category',views.view_category,name="view_category"),
    path('profile',views.profile,name="profile"),
    path('myOrders',views.view_orders,name="view_orders"),
    path('stock/update',views.update_stock,name="update_stock"),
    path('order/history',views.order_history,name="order_history"),

   
]

customer/models.py
from django.db import models

# Create your models here.

class Customer(models.Model):
    first_name = models.CharField(max_length =  20)
    last_name =  models.CharField(max_length =  20)
    email =  models.CharField(max_length =  50)
    gender = models.CharField(max_length = 10)
    city = models.CharField(max_length = 20)
    country = models.CharField(max_length = 20)
    password = models.CharField(max_length = 20)

    class Meta:
        db_table = 'customer_tb'
        
        

customer/views.py
from django.shortcuts import redirect, render

from seller.models import Seller
from .models import Customer
# Create your views here.


def customer_home(request):
    return render(request, 'customer/customer_home.html')


def store(request):
    return render(request, 'customer/store.html')


def product_detail(request):
    return render(request, 'customer/product_detail.html')


def cart(request):
    return render(request, 'customer/cart.html')


def place_order(request):
    return render(request, 'customer/place_order.html')


def order_complete(request):
    return render(request, 'customer/order_complete.html')


def dashboard(request):
    return render(request, 'customer/dashboard.html')


def seller_register(request):
    message = ""
    if request.method == 'POST':  
        fname = request.POST['first_name'] 
        lname = request.POST['last_name']        
        email = request.POST['email']
        gender = request.POST['gender']
        city = request.POST['city']
        country = request.POST['country']
        companyname = request.POST['company-name']
        bank_name = request.POST['bank-name']
        branch_name = request.POST['branch-name']
        account_no = request.POST['account-number']
        ifsc = request.POST['ifsc']
        profile_pic = request.FILES['profile-pic']
        
        seller_exist = Seller.objects.filter(email = email).exists()
        
        if not seller_exist:
            seller = Seller(
                first_name = fname, 
                last_name = lname ,
                company_name = companyname, 
                gender = gender, 
                email = email,
                city = city, 
                country = country, 
                account_no=account_no,
                bank_name=bank_name, 
                branch_name=branch_name, 
                ifsc=ifsc,
                pic=profile_pic
                )
            seller.save()
            message = 'Registration Succesful'

        else:
            message = 'Email already exists'
    
    return render(request, 'customer/seller_register.html',{"status":message})


def seller_login(request):
    message =''
    if request.method == 'POST':
        c_seller_id = request.POST['seller_id'] 
        c_password = request.POST['password']
        
        new_seller = Seller.objects.filter(email = c_seller_id, password = c_password)
        #filter(name the table)
                
        if new_seller.exists():
            print(new_seller)
            # print('before redirect')
            request.session['seller'] = new_seller[0].id
            return redirect('seller:seller_home')
        else:
            # print('inside else block')
            message = 'incorrect password or username'
    
    
    return render(request, 'customer/seller_login.html',{'status':message})


def customer_signup(request):
    message = ""
    if request.method == 'POST':  
        fname = request.POST['fname'] 
        lname = request.POST['lastname']
        email = request.POST['email']
        gender = request.POST['gender']
        city = request.POST['city']
        country = request.POST['country']
        password = request.POST['password']
        
        customer_exist = Customer.objects.filter(email = email).exists()
        
        if not customer_exist:
            customer = Customer(first_name = fname, last_name = lname , gender = gender, email = email, 
                            city = city, country = country, password = password)
            customer.save()
            message = 'Registration Succesful'

        else:
            message = 'Email already exists'
            
    return render(request, 'customer/customer_signup.html',{"status":message})


def customer_login(request):
    message =''
    if request.method == 'POST':
        c_username = request.POST['email'] 
        c_password = request.POST['password']
        
        new_customer = Customer.objects.filter(email = c_username, password = c_password)
        #filter(name the table)
                
        if new_customer.exists():
            print(new_customer)
            # print('before redirect')
            request.session['customer'] = new_customer[0].id
            return redirect('customer:customer_home')
        else:
            # print('inside else block')
            message = 'incorrect password or username'
    
    return render(request, 'customer/customer_login.html',{"status":message})



def forgot_password_customer(request):
    
    return render(request, 'customer/forgot_password_customer.html')


def forgot_password_seller(request):
    return render(request, 'customer/forgot_password_seller.html')

customer/templates/customer/base.html
{% load static%}
<!DOCTYPE HTML>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="pragma" content="no-cache" />
<meta http-equiv="cache-control" content="max-age=604800" />
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<title>GreatKart | One of the Biggest Online Shopping Platform</title>

<link href="{% static 'images/favicon.ico' %}" rel="shortcut icon" type="image/x-icon">

<!-- jQuery -->
<script src="{% static 'js/jquery-2.0.0.min.js' %}" type="text/javascript"></script>

<!-- Bootstrap4 files-->
<script src="{% static 'js/bootstrap.bundle.min.js' %}" type="text/javascript"></script>
<link href="{% static 'css/bootstrap.css' %}" rel="stylesheet" type="text/css"/>

<!-- Font awesome 5 -->
<link href="{% static 'fonts/fontawesome/css/all.min.css' %}" type="text/css" rel="stylesheet">

<!-- custom style -->
<link href="{% static 'css/ui.css' %}" rel="stylesheet" type="text/css"/>
<link href="{% static 'css/responsive.css' %}" rel="stylesheet" media="only screen and (max-width: 1200px)" />

<!-- custom javascript -->
<script src="{% static 'js/script.js' %}" type="text/javascript"></script>

<script type="text/javascript">
/// some script

// jquery ready start
$(document).ready(function() {
	// jQuery code

}); 
// jquery end
</script>

</head>
<body>
   <!-- navbar -->
   {% include 'customer/includes/navbar.html' %}
    {% block content%}

    {% endblock %}

    <!-- footer -->
    {% include 'customer/includes/footer.html' %}
</body>
</html>

customer/templates/customer/cart.html
{% extends 'customer/base.html' %}
{% load static %}

{% block content %}
<section class="section-content padding-y bg">
    <div class="container">

        <!-- ============================ COMPONENT 1 ================================= -->

        <div class="row">
            <aside class="col-lg-9">
                <div class="card">
                    <table class="table table-borderless table-shopping-cart">
                        <thead class="text-muted">
                            <tr class="small text-uppercase">
                                <th scope="col">Product</th>
                                <th scope="col" width="120">Quantity</th>
                                <th scope="col" width="120">Price</th>
                                <th scope="col" class="text-right" width="200"> </th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>
                                    <figure class="itemside align-items-center">
                                        <div class="aside"><img src="{% static './images/items/11.jpg' %}" class="img-sm"></div>
                                        <figcaption class="info">
                                            <a href="#" class="title text-dark">Camera Canon EOS M50 Kit</a>
                                            <p class="text-muted small">Matrix: 25 Mpx <br> Brand: Canon</p>
                                        </figcaption>
                                    </figure>
                                </td>
                                <td>
                                    <!-- col.// -->
                                    <div class="col">
                                        <div class="input-group input-spinner">
                                            <div class="input-group-prepend">
                                                <button class="btn btn-light" type="button" id="button-plus"> <i
                                                        class="fa fa-minus"></i> </button>
                                            </div>
                                            <input type="text" class="form-control" value="1">
                                            <div class="input-group-append">
                                                <button class="btn btn-light" type="button" id="button-minus"> <i
                                                        class="fa fa-plus"></i> </button>
                                            </div>
                                        </div> <!-- input-group.// -->
                                    </div> <!-- col.// -->
                                </td>
                                <td>
                                    <div class="price-wrap">
                                        <var class="price">$1156.00</var>
                                        <small class="text-muted"> $315.20 each </small>
                                    </div> <!-- price-wrap .// -->
                                </td>
                                <td class="text-right">
                                    <a href="" class="btn btn-danger"> Remove</a>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <figure class="itemside align-items-center">
                                        <div class="aside"><img src="{% static './images/items/10.jpg' %}" class="img-sm"></div>
                                        <figcaption class="info">
                                            <a href="#" class="title text-dark">ADATA Premier ONE microSDXC</a>
                                            <p class="text-muted small">Size: 256 GB <br> Brand: ADATA </p>
                                        </figcaption>
                                    </figure>
                                </td>
                                <td>
                                    <!-- col.// -->
                                    <div class="col">
                                        <div class="input-group input-spinner">
                                            <div class="input-group-prepend">
                                                <button class="btn btn-light" type="button" id="button-plus"> <i
                                                        class="fa fa-minus"></i> </button>
                                            </div>
                                            <input type="text" class="form-control" value="1">
                                            <div class="input-group-append">
                                                <button class="btn btn-light" type="button" id="button-minus"> <i
                                                        class="fa fa-plus"></i> </button>
                                            </div>
                                        </div> <!-- input-group.// -->
                                    </div> <!-- col.// -->
                                </td>
                                <td>
                                    <div class="price-wrap">
                                        <var class="price">$149.97</var>
                                        <small class="text-muted"> $75.00 each </small>
                                    </div> <!-- price-wrap .// -->
                                </td>
                                <td class="text-right">
                                    <a href="" class="btn btn-danger"> Remove</a>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <figure class="itemside align-items-center">
                                        <div class="aside"><img src="{% static './images/items/9.jpg' %}" class="img-sm"></div>
                                        <figcaption class="info">
                                            <a href="#" class="title text-dark">Logitec headset for gaming</a>
                                            <p class="small text-muted">Version: CUH-ZCT2E <br> Brand: Sony</p>
                                        </figcaption>
                                    </figure>
                                </td>
                                <td>
                                    <!-- col.// -->
                                    <div class="col">
                                        <div class="input-group input-spinner">
                                            <div class="input-group-prepend">
                                                <button class="btn btn-light" type="button" id="button-plus"> <i
                                                        class="fa fa-minus"></i> </button>
                                            </div>
                                            <input type="text" class="form-control" value="1">
                                            <div class="input-group-append">
                                                <button class="btn btn-light" type="button" id="button-minus"> <i
                                                        class="fa fa-plus"></i> </button>
                                            </div>
                                        </div> <!-- input-group.// -->
                                    </div> <!-- col.// -->
                                </td>
                                <td>
                                    <div class="price-wrap">
                                        <var class="price">$98.00</var>
                                        <small class="text-muted"> $578.00 each</small>
                                    </div> <!-- price-wrap .// -->
                                </td>
                                <td class="text-right">
                                    <a href="" class="btn btn-danger"> Remove</a>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div> <!-- card.// -->

            </aside> <!-- col.// -->
            <aside class="col-lg-3">

                <div class="card">
                    <div class="card-body">
                        <dl class="dlist-align">
                            <dt>Total price:</dt>
                            <dd class="text-right">$69.97</dd>
                        </dl>
                        <dl class="dlist-align">
                            <dt>Tax:</dt>
                            <dd class="text-right"> $10.00</dd>
                        </dl>
                        <dl class="dlist-align">
                            <dt>Total:</dt>
                            <dd class="text-right text-dark b"><strong>$59.97</strong></dd>
                        </dl>
                        <hr>
                        <p class="text-center mb-3">
                            <img src="{% static './images/misc/payments.png' %}" height="26">
                        </p>
                        <a href="{% url 'customer:order_complete' %}" class="btn btn-primary btn-block"> Checkout </a>
                        <a href="{% url 'customer:store' %}" class="btn btn-light btn-block">Continue Shopping</a>
                    </div> <!-- card-body.// -->
                </div> <!-- card.// -->

            </aside> <!-- col.// -->


        </div> <!-- row.// -->
        <!-- ============================ COMPONENT 1 END .// ================================= -->

    </div> <!-- container .//  -->
</section>
<!-- ==============

{% endblock %}

customer/templates/customer/customer_home.html
{% extends 'customer/base.html' %}
{% load static %}

{% block content %}


<!-- ========================= SECTION MAIN ========================= -->
<section class="section-intro padding-y-sm">
    <div class="container">
    
    <div class="intro-banner-wrap">
        <img src="{% static 'images/banners/1.jpg' %}" class="img-fluid rounded">
    </div>
    
    </div> <!-- container //  -->
    </section>
    <!-- ========================= SECTION MAIN END// ========================= -->
    
    <!-- ========================= SECTION  ========================= -->
    <section class="section-name padding-y-sm">
    <div class="container">
    
    <header class="section-heading">
        <a href="{% url 'customer:store' %}" class="btn btn-outline-primary float-right">See all</a>
        <h3 class="section-title">Popular products</h3>
    </header><!-- sect-heading -->
    
        
    <div class="row">
        <div class="col-md-3">
            <div class="card card-product-grid">
                <a href="{% url 'customer:product_detail' %}" class="img-wrap"> <img src="{% static 'images/items/1.jpg' %}"> </a>
                <figcaption class="info-wrap">
                    <a href="{% url 'customer:product_detail' %}" class="title">Just another product name</a>
                    <div class="price mt-1">$179.00</div> <!-- price-wrap.// -->
                </figcaption>
            </div>
        </div> <!-- col.// -->
        <div class="col-md-3">
            <div class="card card-product-grid">
                <a href="{% url 'customer:product_detail' %}" class="img-wrap"> <img src="{% static 'images/items/2.jpg' %}"> </a>
                <figcaption class="info-wrap">
                    <a href="{% url 'customer:product_detail' %}" class="title">Some item name here</a>
                    <div class="price mt-1">$280.00</div> <!-- price-wrap.// -->
                </figcaption>
            </div>
        </div> <!-- col.// -->
        <div class="col-md-3">
            <div class="card card-product-grid">
                <a href="./product-detail.html" class="img-wrap"> <img src="{% static 'images/items/3.jpg' %}"> </a>
                <figcaption class="info-wrap">
                    <a href="./product-detail.html" class="title">Great product name here</a>
                    <div class="price mt-1">$56.00</div> <!-- price-wrap.// -->
                </figcaption>
            </div>
        </div> <!-- col.// -->
        <div class="col-md-3">
            <div class="card card-product-grid">
                <a href="./product-detail.html" class="img-wrap"> <img src="{% static 'images/items/4.jpg' %}"> </a>
                <figcaption class="info-wrap">
                    <a href="./product-detail.html" class="title">Just another product name</a>
                    <div class="price mt-1">$179.00</div> <!-- price-wrap.// -->
                </figcaption>
            </div>
        </div> <!-- col.// -->
        <div class="col-md-3">
            <div class="card card-product-grid">
                <a href="./product-detail.html" class="img-wrap"> <img src="{% static 'images/items/5.jpg' %}"> </a>
                <figcaption class="info-wrap">
                    <a href="./product-detail.html" class="title">Just another product name</a>
                    <div class="price mt-1">$179.00</div> <!-- price-wrap.// -->
                </figcaption>
            </div>
        </div> <!-- col.// -->
        <div class="col-md-3">
            <div class="card card-product-grid">
                <a href="./product-detail.html" class="img-wrap"> <img src="{% static 'images/items/6.jpg' %}"> </a>
                <figcaption class="info-wrap">
                    <a href="./product-detail.html" class="title">Some item name here</a>
                    <div class="price mt-1">$280.00</div> <!-- price-wrap.// -->
                </figcaption>
            </div>
        </div> <!-- col.// -->
        <div class="col-md-3">
            <div class="card card-product-grid">
                <a href="./product-detail.html" class="img-wrap"> <img src="{% static 'images/items/7.jpg' %}"> </a>
                <figcaption class="info-wrap">
                    <a href="./product-detail.html" class="title">Great product name here</a>
                    <div class="price mt-1">$56.00</div> <!-- price-wrap.// -->
                </figcaption>
            </div>
        </div> <!-- col.// -->
        <div class="col-md-3">
            <div class="card card-product-grid">
                <a href="./product-detail.html" class="img-wrap"> <img src="{% static 'images/items/8.jpg' %}"> </a>
                <figcaption class="info-wrap">
                    <a href="./product-detail.html" class="title">Just another product name</a>
                    <div class="price mt-1">$179.00</div> <!-- price-wrap.// -->
                </figcaption>
            </div>
        </div> <!-- col.// -->
    </div> <!-- row.// -->
    
    </div><!-- container // -->
    </section>
    <!-- ========================= SECTION  END// ========================= -->
    
    

{% endblock %}

customer/templates/customer/customer_login.html
{% extends 'customer/base.html' %}

{% block content %}

<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-conten padding-y" style="min-height:84vh">

    <!-- ============================ COMPONENT LOGIN   ================================= -->
        <div class="card mx-auto" style="max-width: 380px; margin-top:100px;">
          <div class="card-body">
          <h4 class="card-title mb-4"> Customer Sign in</h4>
          <form method ='POST'>
            {% csrf_token %}
              <div class="form-group">
                 <input type="email" class="form-control" name='email'placeholder="Email Address" >
              </div> <!-- form-group// -->
              <div class="form-group">
                <input type="password" class="form-control" name='password'placeholder="Password" >
              </div> <!-- form-group// -->
              
              <div class="form-group">
                  <a href="{% url 'customer:forgot_password_customer'%}" class="float-right">Forgot password?</a> 
               
              </div> <!-- form-group form-check .// -->
              <div class="form-group">
                  <button type="submit" class="btn btn-primary btn-block"> Login  </button>
             </div> <!-- form-group// --> 
              {{status}}   
          </form>
          </div> <!-- card-body.// -->
        </div> <!-- card .// -->
    
        
      
    <!-- ============================ COMPONENT LOGIN  END.// ================================= -->
    
    
    </section>
    <!-- ========================= SECTION CONTENT END// ========================= -->
    
    

{% endblock%}

customer/templates/customer/customer_signup.html
{% extends 'customer/base.html' %}

{% block content %}

<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-content padding-y">

    <!-- ============================ COMPONENT REGISTER   ================================= -->
        <div class="card mx-auto" style="max-width:520px; margin-top:40px;">
          <article class="card-body">
            <header class="mb-4"><h4 class="card-title">Customer Sign up</h4></header>
            <form method="POST">
              {% csrf_token %}
                    <div class="form-row">
                        <div class="col form-group">
                            <label>First name</label>
                              <input type="text" name = "fname" class="form-control" placeholder="">
                        </div> <!-- form-group end.// -->
                        <div class="col form-group">
                            <label>Last name</label>
                              <input type="text" name = "lastname" class="form-control" placeholder="">
                        </div> <!-- form-group end.// -->
                    </div> <!-- form-row end.// -->
                    <div class="form-group">
                        <label>Email</label>
                        <input name = "email" type="email" class="form-control" placeholder="">
                        <small class="form-text text-muted">We'll never share your email with anyone else.</small>
                    </div> <!-- form-group end.// -->
                    <div class="form-group">
                        <label class="custom-control custom-radio custom-control-inline">
                          <input class="custom-control-input"   checked="" type="radio" name="gender" value="male">
                          <span class="custom-control-label"> Male </span>
                        </label>
                        <label class="custom-control custom-radio custom-control-inline">
                          <input class="custom-control-input" type="radio" name="gender" value="female">
                          <span class="custom-control-label" > Female </span>
                        </label>
                    </div> <!-- form-group end.// -->
                    <div class="form-row">
                        <div class="form-group col-md-6">
                          <label>City</label>
                          <input type="text" name = "city" class="form-control">
                        </div> <!-- form-group end.// -->
                        <div class="form-group col-md-6">
                          <label>Country</label>
                          <input type="text" name = "country" class="form-control" placeholder="">
                        </div> <!-- form-group end.// -->
                    </div> <!-- form-row.// --> 
                    <div class="form-group">
                        <label>password</label>
                        <input type="password" name = "password" class="form-control" placeholder="Password" >
                      </div> <!-- form-group// -->                   

                    <div class="form-group">
                        <button type="submit" class="btn btn-primary btn-block"> Register  </button>
                    </div> <!-- form-group// -->      
                        {{status}}
                </form>

                
            </article><!-- card-body.// -->
        </div> <!-- card .// -->
        <p class="text-center mt-4">Have an account? <a href="{% url 'customer:customer_login' %}">Log In</a></p>
        <br><br>
    <!-- ============================ COMPONENT REGISTER  END.// ================================= -->
    
    
    </section>
    <!-- ========================= SECTION CONTENT END// ========================= -->
    

{% endblock%}

customer/templates/customer/seller_login.html
{% extends 'customer/base.html' %}

{% block content %}

<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-conten padding-y" style="min-height:84vh">

    <!-- ============================ COMPONENT LOGIN   ================================= -->
        <div class="card mx-auto" style="max-width: 380px; margin-top:100px;">
          <div class="card-body">
          <h4 class="card-title mb-4">Seller Sign in</h4>
          <form method ='POST'>
            {% csrf_token %}
              <div class="form-group">
                 <input type="text" class="form-control" name="seller_id" placeholder="Seller Id" >
              </div> <!-- form-group// -->
              <div class="form-group">
                <input type="password" class="form-control"name="password" placeholder="Password" >
              </div> <!-- form-group// -->
              
              <div class="form-group">
                  <a href="{% url 'customer:forgot_password_seller' %}" class="float-right">Forgot password?</a> 
               
              </div> <!-- form-group form-check .// -->
              <div class="form-group">
                 <button type="submit" class="btn btn-primary btn-block"> Login  </button> 
                   <!-- <a href="{% url 'Seller:seller_home' %}" class="btn btn-primary btn-block">Login</a>-->
              </div> <!-- form-group// -->
              {{status}}       
          </form>
          </div> <!-- card-body.// -->
        </div> <!-- card .// -->
    
         <p class="text-center mt-4">Don't have account? <a href="{% url 'customer:seller_register' %}">Sign up</a></p>
         <br><br>
    <!-- ============================ COMPONENT LOGIN  END.// ================================= -->
    
    
    </section>
    <!-- ========================= SECTION CONTENT END// ========================= -->
    
    

{% endblock%}